module.exports = `<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.23 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 500 - Request processing failed; nested exception is GatewayException [httpStatus=400, errorCode=INVALID_INPUT, message=Barcode not found]</h1><div class="line"></div><p><b>type</b> Exception report</p><p><b>message</b> <u>Request processing failed; nested exception is GatewayException [httpStatus=400, errorCode=INVALID_INPUT, message=Barcode not found]</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b></p><pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is GatewayException [httpStatus=400, errorCode=INVALID_INPUT, message=Barcode not found]
  org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
  org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
  javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
  org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
  javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  williamhill.helios.web.CorsFilter.doFilter(CorsFilter.java:26)
</pre><p><b>root cause</b></p><pre>GatewayException [httpStatus=400, errorCode=INVALID_INPUT, message=Barcode not found]
  williamhill.ssbt.common.openbet.support.OpenbetGatewayErrorHandler.handleError(OpenbetGatewayErrorHandler.java:39)
  org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:615)
  org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:573)
  org.springframework.web.client.RestTemplate.execute(RestTemplate.java:529)
  org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:329)
  williamhill.ssbt.common.openbet.SlipGateway.slipFor(SlipGateway.java:105)
  williamhill.helios.service.core.LboService.slipFor(LboService.java:78)
  williamhill.helios.web.LboController.slipFor(LboController.java:75)
  sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:606)
  org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
  org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
  org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:781)
  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:721)
  org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
  org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
  org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
  org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
  org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
  javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
  org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
  javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  williamhill.helios.web.CorsFilter.doFilter(CorsFilter.java:26)
</pre><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/8.0.23 logs.</u></p><hr class="line"><h3>Apache Tomcat/8.0.23</h3></body></html>
`
